### ISSUE TITLE
Null On-Demand Duration Causes Crash in NowPlayingManager

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-iPhone#101]
#### in NowPlayingManager.(_update in _E448E74EBED534327B59975D6FD254EF)() -> ()

* Number of crashes: 34
* Impacted devices: 34

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55f9db2bf5d3a7f76b130633](https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55f9db2bf5d3a7f76b130633)

**Comment by ewr** [comment]
This bug is still showing up on occasion in 3.4.1. I suspect it may be on-demand audio without a duration? Assigning to the 3.4.2 milestone.

<img width="958" alt="screen shot 2015-09-25 at 7 13 41 am" src="https://cloud.githubusercontent.com/assets/204350/10099166/02b1f3ae-6355-11e5-9473-a06780a70408.png">

**Comment by ewr** [comment]
Found it...

<img width="910" alt="screen shot 2015-09-25 at 1 37 16 pm" src="https://cloud.githubusercontent.com/assets/204350/10107667/a3cd6324-638a-11e5-96bc-3d5fd5574e62.png">

We need to add code to the player to address this possibility, but in the meantime I'll try to address it in the SCPRv4 db.

**Comment by ewr** [comment]
3.4.2 fixes this issue.
