### ISSUE TITLE
Setup local CI server

### ISSUE THREAD

**Issue by chris-fuller** [SCPR/KPCC-iPhone#176]
- Utilize Mac Mini as CI server
- Consider: Xcode bots / Jenkins / Fastlane
- Deliver night builds, but consider only delivering when there are new commits that day
- Utilize Fabric Beta (aka Beta by Crashlytics) for distribution
- Utilize the "treat warnings as errors" build setting
- Utilize the static analyzer

Optional:
- Consider changing automatic build number logic
- Consider setting up manual process for pushing builds to TestFlight (possibly controlled via Slack commands)

**Comment by jeffc-kpcc** [comment]
An update on this: Essentially done, with the following notes:

* We aren't using "treat warnings as errors" at the moment due to Swift 2.3 deprecation warning in existing codebase. Once that's resolved I'll turn it on.

* There are currently 2 static analysis errors, courtesy of A0GoogleAuthenticator.m. Oh, Google. (disapproving look).

* We have opted to only use TestFlight (not Crashlytics) for beta distribution for the time being.

* Builds w/uploads can be triggered manually from my workstation.

* CI occurs each night (well, morning, technically) and shows up as a report in Xcode. There is also a web interface for this.

* Once CI completes and results in a final usable build, IF the resulting build number is greater than that of the most recent TestFlight build (based on Git commit history) it will upload it to TestFlight and make it available for internal testers automatically.

* There is a nifty web-based status board thing we can use to show CI status. I'm not sure how useful it will be, though.

* Right now, if an uploaded build is sent to TestFlight a Slack confirmation message will be sent to me personally. I'm going to give this a few days to make sure that all is working consistently in an automated fashion and then have it start sending to 'mobile-apps'.

I think that this means that CI as defined by this ticket is 'done', but we will likely want to tweak and improve the process over time. Going to pop it into In Review.
