### ISSUE TITLE
Research: SSO via preroll

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#183]
AC: Verify there is a way to launch the SSO process via our current livestream preroll infrastructure.

**Comment by chris-fuller** [comment]
✓ Successfully displayed custom in-app UI instead of opening clickthrough URL in mobile Safari.

Note that the clickthrough URL was matched using a regular expression as apposed to a static string, so we'll need to ensure that the regex that is used is 100% accurate. This will involve some knowledge of the ad server implementation and how it generates the clickthrough URLs.
