### ISSUE TITLE
Research: Auto-submit SSO information

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#184]
AC: Verify that we can auto-submit a logged in user's SSO information to an eloqua form without the user having to take any extra action.

Example form: http://info.americanpublicmediagroup.org/LP=1239?utm_campaign=SCPR%2020160412%20Insider%20-%20Ticket%20Tues%20Showcase%20House&utm_medium=email&utm_source=Eloqua&utm_content=It%27s%20Ticket%20Tuesday&elqTrackId=9ee9cd49cdf448c5bb24433fb695e6af&elq=1f3184b3f8e049b68062746b0045a739&elqaid=21503&elqat=1&elqCampaignId=18675

**Comment by chris-fuller** [comment]
✓ Successfully tested submitting the form from an iOS app.

However, the web application always returns a 200 (OK) status code, even for errors. So this will most likely have to be a "fire and forget" type of action. And there will no really be a way to know 100% for sure that the information was submitted successfully. (We can of course look out for non-200 status codes and handle those cases if/when they do occur.)

The only workaround I can see for this would be to parse/scrape the HTML that is returned, looking for specific text that indicates success or failure, but without an API contract, this workaround would be brittle. I suppose another option would be to look into the Eloqua APIs and see if there is an API endpoint we can utilize instead of relying on the HTML form.
