### ISSUE TITLE
Test and Release V 3.5.0

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#287]
AC

- [x] We have at least 5 internal testers who have run through the entire test plan without encountering a bug that would prevent release
- [x] V 3.5.0 is submitted to apple for approval

**Comment by jeffc-kpcc** [comment]
Per @vsinghkpcc, we are going to push back submission of this update until April 3rd _at the earliest_ (for eminently reasonable not-switching-horses-in-the-middle-of-a-pledge-drive reasons).

Will continue testing this release until then.

**Comment by jeffc-kpcc** [comment]
So, as I expected, the source of the problem with the legacy KPCC app is because we’re getting http:// URLs linking to external resources for certain podcasts.

This is coming from the server, so I presume that if we had different URLs it’d work fine.

In a couple of cases we do get https:// URLs, but they seem to be redirects. I’ve not checked, but I think they’re redirecting to non-TLS URLs.

Not sure how to proceed. We have a few options, though.

1. Change the URLs server-side.

2. Resubmit the app with an ATS exemption that will allow us to load HTTP from the domain(s) in question.

3. Resubmit the app with a _global_ ATS exemption that will allow us to load HTTP from _any_ domain, if we don’t have an https:// URL for it.

The downside of options 2 and 3 is that it’d have to make it through app review, but I would think/hope Apple would be understanding as this is not unlike ATS exemptions for web content (which they do allow for) and podcast clients certainly can’t control for every URL they load.

The downside of option 2, specifically, is that it would require a resubmission if we were ever to add another podcast/program with a non-exempted URL.

**Comment by jeffc-kpcc** [comment]
Submitted to Apple with a request for an ATS exemption, due to the nature of our app pulling from numerous outside servers out of our control (of which some are not TLS/SSL).

**Comment by jeffc-kpcc** [comment]
Approved by Apple, completing this ticket. Waiting for unrelated stream errors to be resolved before release.

**Comment by vsinghkpcc** [comment]
Given this has been approved, we'll release once the stream issues are resolved. In that case, we can consider this done.
